# Generated by Django 3.2.20 on 2023-08-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_adventure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventure',
            options={'ordering': ['-date']},
        ),
    ]
